/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LegalImport } from './routes/legal'
import { Route as NoteIdImport } from './routes/$noteId'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const LegalRoute = LegalImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRoute,
} as any)

const NoteIdRoute = NoteIdImport.update({
  id: '/$noteId',
  path: '/$noteId',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$noteId': {
      id: '/$noteId'
      path: '/$noteId'
      fullPath: '/$noteId'
      preLoaderRoute: typeof NoteIdImport
      parentRoute: typeof rootRoute
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$noteId': typeof NoteIdRoute
  '/legal': typeof LegalRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$noteId': typeof NoteIdRoute
  '/legal': typeof LegalRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$noteId': typeof NoteIdRoute
  '/legal': typeof LegalRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$noteId' | '/legal'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$noteId' | '/legal'
  id: '__root__' | '/' | '/$noteId' | '/legal'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NoteIdRoute: typeof NoteIdRoute
  LegalRoute: typeof LegalRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NoteIdRoute: NoteIdRoute,
  LegalRoute: LegalRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$noteId",
        "/legal"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$noteId": {
      "filePath": "$noteId.tsx"
    },
    "/legal": {
      "filePath": "legal.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
